### ISSUE TITLE
How to pass coordinate transformation or stride

### ISSUE THREAD

**Issue by highsource** [derhuerst/wfs-gml-to-geojson#3]
Where do we discuss development? In issues or in Gitter chat?

Anyway, I'm thinking about signatures of parse methods. In `parse-gml-polygon` it's always

```
parseSomething(data, transformCoords, stride)
```

I don't think this will work this ways. I think we will most probably need more "optional parameters".
For instance:

* Some kind of reference resolver. Geometries or parts thereof may be provided by reference, both internal and external.
* Context SRS. If SRS is not provided, it is assumed to be equal to the SRS of the parent structure.

Probably much more. Maybe we'll also need to have some state object (for instance how do we dereference internal references?).

If we start adding all these things as method parameters, we'll have a rat tail of them, hanging all over.

What I was thinking was using some kind of `options` or `context` object as the last optional parameter. It will hold all other "optional parameters". Signatures will be then like:

```
parseSomething(data, options);
```

For example:

```
parseSomething(data, {transformCoords: noTransform, stride: 3});
```

What do you think?

**Comment by derhuerst** [comment]
Sounds very reasonable. I think having `parseSomething(data, opt, ctx)` is pretty future-proof.

`ctx` would be the parsing context, e.g. coordinate system, items to be referenced, etc. If you want to amend the `ctx` of only "child parsers", you can do this:

```js
const childCtx = Object.create(ctx)
childCtx.additionalProp = 'some-value'
parseChild(data.child, opt, childCtx)
```

**Comment by derhuerst** [comment]
~~PR welcome that changes the signature of the parsing functions.~~ Confused this repo with `parseGmlPolygon`.

**Comment by highsource** [comment]
Ok. I'd only suggest `(data, ctx, opt)`, not `(data, opt, ctx)`.
