### ISSUE TITLE
Parse gml:Point / gml:pos

### ISSUE THREAD

**Issue by highsource** [derhuerst/wfs-gml-to-geojson#6]

**Comment by derhuerst** [comment]
This recreates some of the `parse-gml-polygon` code? Why not submit a PR there?

Do you want push access in order not to manage a fork?

**Comment by highsource** [comment]
> Do you want push access in order not to manage a fork?

Yes, that would be good for the initial development stages. To be honest I only have experience with forks to submit patches to already established projects.

> This recreates some of the `parse-gml-polygon` code? Why not submit a PR there?

It's actually work in progress, I'm experimenting with signatures etc. so I did not give it much thought yet.

How would you do it? Make `wfs-gml-to-geojson` require `parse-gml-polygon`?

For me it looks like `wfs-gml-to-geojson` is actually a superset of `parse-gml-polygon`. So if `wfs-gml-to-geojson` is complete there will be no much need in `parse-gml-polygon`, will there?
So at the moment I'd tend to implement `wfs-gml-to-geojson` as an independent project - even if this would be copy-pasting/recreating some of the code from `parse-gml-polygon`.

**Comment by derhuerst** [comment]
> To be honest I only have experience with forks to submit patches to already established projects.

You just push to a branch, visit https://github.com/user/repo/compare/branch-name?expand=1 and pull request from there.

> How would you do it? Make `wfs-gml-to-geojson` require `parse-gml-polygon`?

Yup, that sounds sensible right now.

> So if `wfs-gml-to-geojson` is complete there will be no much need in `parse-gml-polygon`, will there?

Depends how much `wfs-gml-to-geojson` will do. If it will be the same minimal lib (no XML parsing, no `proj4` included, etc) than I guess `parse-gml-polygon` will become obsolete.

**Comment by highsource** [comment]
@derhuerst Could you please add me as a collaborator to the `parse-gml-polygon` as well?

**Comment by derhuerst** [comment]
Closing in favor of derhuerst/parse-gml-polygon#14.
